
export const DATA_EN = {
    'home.first.login.button' : 'Sign In',
    'home.container.content.title' : 'Unlimited movies, series and more',
    'home.container.content.first' : 'Enjoy Netflix wherever you want. Can be cancelled at any time',
    'home.container.content.second' : 'Are you strong? Enter your email address to start or reactivate your membership.',
    'home.container.content.placeholder' : 'E-mail address',
    'home.container.content.button' : 'Get started',
    'signup.container.title' : 'Create a password to start your membership',
    'signup.container.untertitle.first' : 'Just a few more steps and you\'ve made it!',
    'signup.container.untertitle.second' : 'We also have paperwork boring.',
    'signup.container.checkbox' : 'Yes, please send me special offers from Netflix via email',
    'signup.container.container.button': 'Next',
    'signin.container.title' : 'Sign In',
    'signin.container.container.button': 'Next',
    'signin.container.checkbox' : 'Remenber me',
    'navbar.button.signup' : 'Sign In',
    'navbar.button.choose.pay' : 'Log Out',
    'private.home.h1' : 'Netflix',
    'private.home.li.one' : 'Homepage',
    'private.home.li.second' : 'series',
    'private.home.li.third' : 'movies',
    'private.home.li.four' : 'New and Popular',
    'private.home.li.five' : 'my list',
    'private.home.movie.information.h1' : 'The Baron of the R2',
    'private.home.movie.information.p' : 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
    'private.home.movie.information.button.one' : 'Play',
    'private.home.movie.information.button.second' : 'Next',
    'private.home.private.home.box.h2.one' : 'Trending',
    'private.home.private.home.box.h2.second' : 'Best Dramas',
    'private.home.private.home.box.h2.third' : 'Best Kids Movies',
    'private.home.private.home.box.h2.four' : 'Coming in Theatres...',
    'private.home.private.home.box.h2.five' : 'Best Dramas Movies...',
    'list.component.overlay.h1' : 'my list'
}